name: CI
run-name: ${{ github.actor }} running CI
on: [push]

env: 
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Run CI on MacOS
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update stable

      - name: Install HDF5
        run: |
          brew install hdf5

      - name: Build
        run: cargo build --verbose

      - name: Check Format
        run: cargo fmt -- --check